### ISSUE TITLE
Use json crate

### ISSUE THREAD

**Issue by mominul** [OpenBangla/bengali-phonetic-parser-rs#1]
We currently use the [`serde-json`](https://crates.io/crates/serde_json) crate to parse the json files, but it is a heavy weight crate & we don't use it's main serialization feature. So we can use the [`json` crate](https://crates.io/crates/json) which is enough and fast for our needs.

I think handling this issue is very easy as I have done the `json` to `serde-json` transition before, so the contributor [should get the idea from this commit!](https://github.com/OpenBangla/rupantor-rs/commit/2b87731ee117d729f88bc5d1c45361b0aff75cbc)

**Comment by Saumen95** [comment]
Work on progress...

**Comment by gulshan** [comment]
Please check my port of avro parser in rust here- https://github.com/gulshan/okkhor-lib . It's a bit opinionated though. Instead of json, it uses embedded data. So, no need to parse json and no external dependencies.

**Comment by mominul** [comment]
@gulshan your crate is really interesting! But I think we now have the intention to have the json files for it's flexibility.
If we want to switch this approach, your crate will be a great option!

**Comment by mominul** [comment]
@gulshan I have done some benchmarking, This is what I get when converting `ami` & `bistarito` words with `okkhor-lib` & `rupantor`:
```
test bench_okkhor_ami         ... bench:       1,999 ns/iter (+/- 304)
test bench_okkhor_bistarito   ... bench:       6,613 ns/iter (+/- 191)
test bench_rupantor_ami       ... bench:       1,510 ns/iter (+/- 257)
test bench_rupantor_bistarito ... bench:       6,274 ns/iter (+/- 718)
```
`okkhor-lib` is having a noticeable slowdown, are we missing any possible optimization in `okkhor-lib`? I thought initially that `okkhor-lib` should be faster as it compiles down all the patterns, but this was not the case...

**Comment by gulshan** [comment]
@mominul No idea why this is happening. I'll try to figure it out.

**Comment by gulshan** [comment]
It seems okkhor parse function is a bit different than rupantor, specially finding the "pattern match" at the start of an string part. okkhor is doing better with long and complex words and sentences in my benchmarks. I shall upload the benchmark codes.

**Comment by gulshan** [comment]
My benchmark code- https://github.com/gulshan/okkhor-lib/blob/master/benches/benching.rs
